### ISSUE TITLE
Spectating someone in Cyberspace causes view rotation next spawn

### ISSUE THREAD

**Issue by Joshua-Ashton** [punyhumangames/Dystopia#1]

**Comment by Joshua-Ashton** [comment]
1.5.2 will have fix in testing

**Comment by Cokemonkey11** [comment]
Seen still on live stable version (I think that's 1.5.1)

**Comment by Cokemonkey11** [comment]
Looks fixed in live stable.

**Comment by jumpandspintowin** [comment]
Seems like it may still occur in the current stable build (1.5.2)
https://youtu.be/A1OrOagmz9U

**Comment by urinal-cake** [comment]
This particular issue should be fixed, when the player spawns their view should be correct. Although, the bug of players view still getting screwed up in cyberspace still exists.
